# Generated by Django 5.2.4 on 2025-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('in-person', 'In-person')], default='in-person', max_length=10),
        ),
    ]
