# Generated by Django 5.2.4 on 2025-08-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='credit_required',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
