# Generated by Django 5.2.4 on 2025-08-07 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_credit_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='customer_reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
    ]
