# Generated by Django 5.2.4 on 2025-08-07 20:44

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_customer_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customer_reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
