# Generated by Django 5.2.4 on 2025-07-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='street',
        ),
    ]
