# Generated by Django 5.2.4 on 2025-08-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_address_user_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_credits',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=6),
        ),
    ]
