# Generated by Django 5.2.4 on 2025-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_credits',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=6),
        ),
    ]
