# Generated by Django 5.2.4 on 2025-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_time_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_credits',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=4),
        ),
    ]
